[workspace]
members = [
    "stepper",
    "main",
    "motor",
    "dc_motor",
    "encoder",
    "rotary_encoder",
    "wheel",
    "servo",
]

[profile.dev]
debug = true

[profile.release]
codegen-units = 1
debug = true
lto = true

