[package]
edition = "2021"
name = "servo"
version = "0.1.0"

[dependencies]
num-traits = { version = "0.2", default-features = false }
pid = "3.0.0"

motor = { path = "../motor" }
encoder = { path = "../encoder" }
wheel = { path = "../wheel" }

