[package]
name = "interfacing"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["bincode/std"]

[dependencies]
bincode = { vesion = "1.3.3", features = ["derive"], default-features = false}
heapless = "0.7.10"
reed-solomon = "0.2.1"

