[package]
name = "interfacing"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["bincode/std"]

[dependencies]
bincode = { version = "2.0.0-rc.1", features = ["derive"], default-features = false}
heapless = "0.7.10"
reed-solomon = "0.2.1"
serial_int = "2.0.0"

